name: nestjs-cars
run-name: ${{ github.actor }} pushed a new version

on:
  push:
    branches: [ main, test* ]
  pull_request:
    branches:
      - main
      - test*

env:
  AZURE_WEBAPP_NAME: nestjs-cars-code   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.12.1'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout    # checks out your repository and downloads it to the runner
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Build
        run: |
          npm install
          npm run build
          echo "🎉 build successful"

      - name: Linter
        run: |
          npm run lint

      - name: Unit tests
        run: |
          npm run test:cov

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: nestjs-cars
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: nestjs-cars

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2.2.5
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
