name: nestjs-cars
run-name: ${{ github.actor }} pushed a new version

on:
  push:
    branches: [ main, test* ]
  pull_request:
    branches:
      - main
      - test*

env:
  AZURE_WEBAPP_NAME: nestjs-cars-code   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.12.1'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout    # checks out your repository and downloads it to the runner
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Build
        run: |
          npm install
          npm run build
          echo "🎉 build successful"

      - name: Linter
        run: |
          npm run lint

      - name: Unit tests
        run: |
          npm run test:cov

  deploy_container:
    runs-on: ubuntu-latest
    needs: build_and_test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login docker
        uses: docker/login-action@v2
#        uses: azure/docker-login@v1
        with:
#          login-server: nestjscarsregistry.azurecr.io
          registry: nestjscarsregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Prepare app image
        run: |
          docker build . -t nestjscarsregistry.azurecr.io/nestjs-cars-image:${{ github.sha }}
          docker push nestjscarsregistry.azurecr.io/nestjs-cars-image:${{ github.sha }}     

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2.2.5
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          images: 'nestjscarsregistry.azurecr.io/nestjs-cars-image:${{ github.sha }}'
